version: 2.1

parameters:
  project-name:
    type: string
    required: true
  ruby-version:
    type: string
    required: true
  bundler-version:
    type: string
    required: true
  # TODO: check if this parameter can be removed
  rails-version:
    type: string
    required: true

jobs:
  build:
    working_directory: /tmp/app
    environment:
      DOCKER_REGISTRY: 396522184519.dkr.ecr.eu-west-1.amazonaws.com
    docker:
      - image: cimg/aws:2023.09
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /tmp/caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /tmp/caches/app.tar | true
      - run:
          name: Download shared Dockerfile and utils
          command: |
            git clone --depth 1 --branch test-ci-build git@github.com:CapSens/circleCi-dynamic-config.git dynamic_configs
            cp -R dynamic_configs/.dockerdev ./
            rm -rf dynamic_configs
      - run:
          name: Build application Docker image
          command: |
            docker build -t "${DOCKER_REGISTRY}/<< pipeline.parameters.project-name >>:${CIRCLE_BRANCH}-${CIRCLE_SHA1}" \
              --build-arg RUBY_VERSION=<< pipeline.parameters.ruby-version >> \
              --build-arg RAILS_VERSION=<< pipeline.parameters.rails-version >> \
              --build-arg NODE_MAJOR=16 \
              --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} \
              --file .dockerdev/Dockerfile \
              .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /tmp/caches
            docker save -o /tmp/caches/app.tar ${DOCKER_REGISTRY}/<< pipeline.parameters.project-name >>:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rm -rf ~/.aws
              aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
              docker push ${DOCKER_REGISTRY}/<< pipeline.parameters.project-name >>:${CIRCLE_BRANCH}-${CIRCLE_SHA1}
            # fi

workflows:
  version: 2
  'workflow':
    jobs:
        - build:
            context:
              - Github
              - AWS_ECR
