version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

parameters:
  project-name:
    type: string
    default: 'my-project' # must match mysql_username and mysql_database into database.yml.ci
  ruby-version:
    type: string
    default: "2.7.1"
  bundler-version:
    type: string
    default: "2.2.16"
  branches-for-assets:
    type: string
    default: "('master:production' 'staging')" # add any branch you want assets to be compiled on
  assets-buckets:
    type: string
    default: "()" # must match branches-for-assets size and order, if not filled, it will be (assets-bucket-production assets-bucket-staging)
  assets-bucket-staging:
    type: string
    default: ""
  assets-bucket-production:
    type: string
    default: ""
  ignored_cves:
    type: string
    default: ""
  install-redis:
    type: boolean
    default: false
  install-tesseract:
    type: boolean
    default: false
  tests-parallelism:
    type: integer
    default: 1
  precompile-assets:
    type: boolean
    default: true
  deploy-on-beanstalk:
    type: boolean
    default: false
  beanstalk-env-staging:
    type: string
    default: ""
  beanstalk-app-staging:
    type: string
    default: ""
  beanstalk-env-production:
    type: string
    default: ""
  beanstalk-app-production:
    type: string
    default: ""
  custom-deploy-branch:
    type: string
    default: ""
  beanstalk-platform-version:
    type: string
    default: ""

commands: # a reusable command with parameters
  setup_env:
    steps:
      - checkout
      - run:
          name: Database Config
          command: cp config/database.yml.ci config/database.yml
      - run:
          name: Install Bundler
          # mettre ici la meme version que celle utilisée pour générer le gemfile.lock sinon le cache ne marchera pas
          command: gem install bundler:<< pipeline.parameters.bundler-version >>
      - restore_cache:
         key: my-app-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: my-app-{{ checksum "Gemfile.lock" }}
          paths:
              - vendor/bundle
      - when:
          condition: << pipeline.parameters.install-redis >>
          steps:
            - run:
                name: Redis
                command: |
                  apt-get install -y redis-server
                  service redis-server start
      - when:
          condition: << pipeline.parameters.install-tesseract >>
          steps:
            - run:
                name: Tesseract OCR
                command: |
                  apt-get install -y tesseract-ocr
      - run:
          name: Database initialization
          command: bundle exec rake db:create db:migrate
jobs:
  spec:
    working_directory: ~/<< pipeline.parameters.project-name >>
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: << pipeline.parameters.project-name >>
          MYSQL_USER: << pipeline.parameters.project-name >>
          MYSQL_PASSWORD: << pipeline.parameters.project-name >>

    parallelism: << pipeline.parameters.tests-parallelism >>
    steps:
      - setup_env
      - run:
          name: Test
          command: |
            yarn
            circleci tests glob "spec/**/*_spec.rb" | circleci tests split > /tmp/tests-to-run
            bundle exec rspec $(cat /tmp/tests-to-run)
  assets:
    working_directory: ~/<< pipeline.parameters.project-name >>
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: << pipeline.parameters.project-name >>
          MYSQL_USER: << pipeline.parameters.project-name >>
          MYSQL_PASSWORD: << pipeline.parameters.project-name >>
    steps:
      - run:
          name: "empty step"
          command: "echo ok"
      - when:
          condition: << pipeline.parameters.precompile-assets >>
          steps:
            - setup_env
            - run:
              name: "Compile and serve assets"
              command: |
                branches=<< pipeline.parameters.branches-for-assets >>
                assetsBuckets=<< pipeline.parameters.assets-buckets >>
                if [ ${#assetsBuckets[@]} -eq 0 ]; then
                  assetsBuckets=('<< pipeline.parameters.assets-bucket-production >>' '<< pipeline.parameters.assets-bucket-staging >>')
                fi

                for i in "${!branches[@]}"; do
                  if [ $CIRCLE_BRANCH == ${branches[$i]%%:*} ]; then
                    export ASSETS_ENV=${branches[$i]##*:}
                    export S3_ASSETS_BUCKET=${assetsBuckets[$i]}
                  fi
                done

                if [[ -z "${ASSETS_ENV}" ]]; then
                  echo "ASSETS_ENV var has not been set. Skipping assets compilation."
                  exit 0
                else
                  echo "ready to compile assets for env $ASSETS_ENV on assets bucket $S3_ASSETS_BUCKET"

                  yarn
                  RAILS_ENV=${ASSETS_ENV} bundle exec rake db:create db:migrate
                  RAILS_ENV=${ASSETS_ENV} bundle exec rake assets:clobber assets:precompile
                  aws s3 cp public/assets/ s3://${S3_ASSETS_BUCKET}/assets/ --recursive --acl public-read --cache-control max-age=${CACHE_MAX_AGE:-86400}

                  if [ -d "public/packs" ]; then
                    aws s3 cp public/packs/ s3://${S3_ASSETS_BUCKET}/packs/ --recursive --acl public-read --cache-control max-age=${CACHE_MAX_AGE:-86400}
                  else
                    echo "No public/packs directory, skipping packs upload."
                  fi
                fi
  security_check:
    working_directory: ~/<< pipeline.parameters.project-name >>
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: "Audit Securité du Gemfile"
          command: |
            gem install bundler-audit

            IGNORE="<< pipeline.parameters.ignored_cves >>"
            set +e
            OAUTH_CRSF_FOUND=`grep -c -m1 omniauth-rails_csrf_protection Gemfile`
            SHRINE_CHECK=`grep -hrc derivation_endpoint -- config/initializers app/uploaders | awk '{s+=$1} END {print s}'`
            set -e
            if [ $OAUTH_CRSF_FOUND -eq 1 ]; then
              IGNORE="$IGNORE CVE-2015-9284"
            fi
            if [ $SHRINE_CHECK -eq 0 ]; then
              IGNORE="$IGNORE CVE-2020-15237"
            fi
            if [ -n "$IGNORE" ]; then
              IGNORE="--ignore $IGNORE"
            fi

            bundle audit --update $IGNORE
      - run:
          name: "Audit de securité de l'application"
          command: |
            gem install brakeman -v 5.4.1
            mkdir -p security
            brakeman -o security/brakeman.html || true
      - store_artifacts:
          path: security/brakeman.html
  beanstalk-deploy-asked:
    working_directory: ~/<< pipeline.parameters.project-name >>
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
        environment:
          RAILS_ENV: test
    steps:
      - run:
          name: Check if deployment is required
          command: "[ << pipeline.parameters.deploy-on-beanstalk >> = true ]"

workflows:
    version: 2
    'workflow':
        jobs:
            - spec
            - security_check
            - assets:
                context:
                  - ASSETS
                filters:
                  branches:
                    only: ['master', 'staging']
                requires: ['spec', 'security_check']
            - beanstalk-deploy-asked:
                filters:
                  branches:
                    only: [master, staging, << pipeline.parameters.custom-deploy-branch >>]
                requires: ['spec', 'security_check']
            - eb/deploy:
                name: eb-deploy-staging
                context: AWS_BEANSTALK
                application-name: << pipeline.parameters.beanstalk-app-staging >>
                environment-name: << pipeline.parameters.beanstalk-env-staging >>
                filters:
                  branches:
                    only: [staging]
                platform-version: << pipeline.parameters.beanstalk-platform-version >>
                requires: ["beanstalk-deploy-asked"]
            - eb/deploy:
                context: AWS_BEANSTALK
                application-name: << pipeline.parameters.beanstalk-app-production >>
                environment-name: << pipeline.parameters.beanstalk-env-production >>
                filters:
                  branches:
                    only: [master, main]
                platform-version: << pipeline.parameters.beanstalk-platform-version >>
                requires: ["beanstalk-deploy-asked"]
