version: 2.1

parameters:
  project-name:
    type: string
    default: 'my-project' # must match pg_username and pg_database into database.yml.ci
  ruby-version:
    type: string
    default: "2.7.1"
  bundler-version:
    type: string
    default: "2.2.16"
  assets-bucket-staging:
    type: string
    default: ""
  assets-bucket-production:
    type: string
    default: ""
  ignored_cves:
    type: string
    default: ""
  install-redis:
    type: boolean
    default: false
  install-tesseract:
    type: boolean
    default: false
  tests-parallelism:
    type: integer
    default: 1
  resource-class:
    type: string
    default: "medium"
  assets-resource-class: # platforms with webpacker needs a bigger instance than small
    type: string
    default: "small"
  clever-cloud-app-staging:
    type: string
    default: ""
  clever-cloud-app-production:
    type: string
    default: ""
  deploy-on-clever-cloud:
    type: boolean
    default: false

commands: # a reusable command with parameters
  setup_env:
    steps:
      - checkout
      - run:
          name: Database Config
          command: cp config/database.yml.ci config/database.yml
      - run:
          name: Install Bundler
          # mettre ici la meme version que celle utilisée pour générer le gemfile.lock sinon le cache ne marchera pas
          command: gem install bundler:<< pipeline.parameters.bundler-version >>
      - restore_cache:
         key: my-app-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: my-app-{{ checksum "Gemfile.lock" }}
          paths:
              - vendor/bundle
      - when:
          condition: << pipeline.parameters.install-redis >>
          steps:
            - run:
                name: Redis
                command: |
                  apt-get install -y redis-server
                  service redis-server start
      - when:
          condition: << pipeline.parameters.install-tesseract >>
          steps:
            - run:
                name: Tesseract OCR
                command: |
                  apt-get install -y tesseract-ocr
      - run:
          name: Database initialization
          command: bundle exec rake db:create db:migrate

jobs:
  spec:
    working_directory: ~/<< pipeline.parameters.project-name >>
    resource_class: << pipeline.parameters.resource-class >>
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
        environment:
          PGHOST: localhost
          PGUSER: << pipeline.parameters.project-name >>
          RAILS_ENV: test
      - image: cimg/redis:6.2.6
      - image: postgres:12
        environment:
          POSTGRES_USER: << pipeline.parameters.project-name >>
          POSTGRES_DB: << pipeline.parameters.project-name >>
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    parallelism: << pipeline.parameters.tests-parallelism >>
    steps:
      - setup_env
      - run:
          name: Test
          command: |
            yarn
            circleci tests glob "spec/**/*_spec.rb" | circleci tests split > /tmp/tests-to-run
            bundle exec rspec $(cat /tmp/tests-to-run)
  assets:
    working_directory: ~/<< pipeline.parameters.project-name >>
    resource_class: << pipeline.parameters.assets-resource-class >>
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
        environment:
          PGHOST: localhost
          PGUSER: << pipeline.parameters.project-name >>
          RAILS_ENV: test
      - image: postgres:12
        environment:
          POSTGRES_USER: << pipeline.parameters.project-name >>
          POSTGRES_DB: << pipeline.parameters.project-name >>
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - setup_env
      - run:
          name: "Compile and serve assets"
          command: |
            if [ $CIRCLE_BRANCH == staging ]
            then
              export ASSETS_ENV=staging
              export S3_ASSETS_BUCKET=<< pipeline.parameters.assets-bucket-staging >>
            elif [ $CIRCLE_BRANCH == master ]
            then
              export ASSETS_ENV=production
              export S3_ASSETS_BUCKET=<< pipeline.parameters.assets-bucket-production >>
            else
              exit 0
            fi

            yarn
            RAILS_ENV=${ASSETS_ENV} bundle exec rake db:create db:migrate
            RAILS_ENV=${ASSETS_ENV} bundle exec rake assets:clobber assets:precompile
            aws s3 --endpoint-url https://cellar-c2.services.clever-cloud.com cp public/assets/ s3://${S3_ASSETS_BUCKET}/assets/ --recursive --acl public-read --cache-control max-age=${CACHE_MAX_AGE:-86400}

            if [ -d "public/packs" ]; then
              aws s3 --endpoint-url https://cellar-c2.services.clever-cloud.com cp public/packs/ s3://${S3_ASSETS_BUCKET}/packs/ --recursive --acl public-read --cache-control max-age=${CACHE_MAX_AGE:-86400}
            else
              echo "No public/packs directory, skipping packs upload."
            fi
  security_check:
    working_directory: ~/<< pipeline.parameters.project-name >>
    resource_class: small
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: "Audit Securité du Gemfile"
          command: |
            gem install bundler-audit

            IGNORE="<< pipeline.parameters.ignored_cves >>"
            set +e
            OAUTH_CRSF_FOUND=`grep -c -m1 omniauth-rails_csrf_protection Gemfile`
            SHRINE_CHECK=`grep -hrc derivation_endpoint -- config/initializers app/uploaders | awk '{s+=$1} END {print s}'`
            set -e
            if [ $OAUTH_CRSF_FOUND -eq 1 ]; then
              IGNORE="$IGNORE CVE-2015-9284"
            fi
            if [ $SHRINE_CHECK -eq 0 ]; then
              IGNORE="$IGNORE CVE-2020-15237"
            fi
            IGNORE="$IGNORE CVE-2023-26141"
            IGNORE="$IGNORE CVE-2023-51763"
            if [ -n "$IGNORE" ]; then
              IGNORE="--ignore $IGNORE"
            fi

            bundle audit --update $IGNORE
      - run:
          name: "Audit de securité de l'application"
          command: |
            gem install brakeman -v 5.4.1
            mkdir -p security
            brakeman -o security/brakeman.html || true
      - store_artifacts:
          path: security/brakeman.html
  clever_cloud_deploy:
    working_directory: ~/<< pipeline.parameters.project-name >>
    resource_class: small
    docker:
      - image: capsens/ruby-node-yarn:<< pipeline.parameters.ruby-version >>
    steps:
      - checkout
      - run:
          name: clever deploy
          command: |
            if [ << pipeline.parameters.deploy-on-clever-cloud >> = false ]
            then
              echo "Clever Cloud deploy not required for this platform"
              exit 0
            fi

            if [ $CIRCLE_BRANCH == staging ]
            then
              export CLEVER_APP_ID=<< pipeline.parameters.clever-cloud-app-staging >>
            elif [ $CIRCLE_BRANCH == master ]
            then
              export CLEVER_APP_ID=<< pipeline.parameters.clever-cloud-app-production >>
            fi

            # CLEVER_SSH_KEY variable can be generated with the commande : `cat /path/to/private/key | sed 's/$/\\n/' | tr -d '\n'`
            echo $CLEVER_SSH_KEY | sed 's/\\n/\n/g' > ~/.ssh/clever
            chmod 400 ~/.ssh/clever
            ssh-add ~/.ssh/clever

            if [ ! -n "$(grep "^push-n2-par-clevercloud-customers" ~/.ssh/known_hosts)" ]
            then
              ssh-keyscan push-n2-par-clevercloud-customers.services.clever-cloud.com >> ~/.ssh/known_hosts 2>/dev/null
            fi

            git config user.email "infra@capsens"
            git remote add clever git+ssh://git@push-n2-par-clevercloud-customers.services.clever-cloud.com/$CLEVER_APP_ID.git
            git push -u clever $CIRCLE_BRANCH:master --force

workflows:
    version: 2
    'workflow':
        jobs:
            - spec
            - security_check
            - assets:
                context:
                  - CLEVER_CLOUD
                filters:
                  branches:
                    only: [master, staging]
                requires: ['spec', 'security_check']
            - clever_cloud_deploy:
                context: CLEVER_CLOUD
                filters:
                  branches:
                    only: [master, staging]
                requires: ['assets']
